services:
  postgres:
    image: postgres:15
    container_name: nutrition-db
    restart: always
    environment:
      POSTGRES_DB: nutrition_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  nutrition-app:
    build:
      context: ./nutrition-app
    container_name: nutrition-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nutrition_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: always

  inference-app:
    build:
      context: ./inference-app
    container_name: inference-app
    depends_on:
      - nutrition-app
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./nutrition-app-frontend
    container_name: nutrition-app-frontend
    depends_on:
      - nutrition-app
    ports:
      - "5173:80"
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  db-init:
    image: postgres:15
    container_name: db-init
    depends_on:
      - postgres
      - nutrition-app
    volumes:
      - ./init-sql/data.sql:/data.sql
    entrypoint: >
      bash -c "
        until pg_isready -h postgres -U postgres; do sleep 1; done;
        sleep 15;
        psql -h postgres -U postgres -d nutrition_db -f /data.sql
      "
    environment:
      PGPASSWORD: postgres

volumes:
  pgdata:
