spring:
  application:
    name: nutrition-app
  datasource:
    url: jdbc:postgresql://localhost:5432/nutrition_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret-key: ae5cb0017eb75df7043c76aec88cd2082d1ada09c5bb506d1596331227d89021d0461c2f981e01bc196fad8db08f61b6f4538bfb56587a3b1272808a9e6639ce73f19f9bc75f184c8844ab6c27be478a49979a32fa0a04e4fe197e18087e20b415ec19d47c07a15cbc5cae3563d225a6dc9e041a0b4a0f2b7b801b7099e94b24d396761ea66485f054df804e4a2f0b502b2dd6f04eecf2784479df4fb70db1a918bdfab11b4f016683af46487225b93c749cf8276a49bf485c886df3f436ba5a5865069413a945c58dfb173ef59a890b5a7bfceae11a93d543916bdfd05611e1362db2dc576ddaf6e11fcddba8c959d444c3dee12fd8378871234fa0b476657d
    token-expiration-days: 1
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html

whitelisted-paths: /auth/**, /swagger-ui/**, /v3/api-docs/**, /v3/api-docs.yaml, /swagger-ui.html, /bus/**, /actuator/**
reset-password-url: http://localhost:5173/reset-password
reset-password-email-title: 'Password reset email - DEAL'
reset-password-email-body: 'Reset your password using: '
deal-mail: no-reply@deal.com
app-mail: your@email.com

logging:
  level:
    root: INFO
    org.nutrition: DEBUG
